stop using action

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -3,31 +3,46 @@ on:
 - pull_request
 
 jobs:
-  docs:
-    runs-on: ubuntu-latest
+  #docs:
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #  - uses: actions/checkout@v1
+  #  - uses: ammaraskar/sphinx-action@master
+  #    with:
+  #      docs-folder: "docs/"
+  #      build-command: "sphinx-build -E -b html -d _build/doctrees   . _build/html"
+  #  
+  #  - name: Commit documentation changes
+  #    run: |
+  #      git clone https://github.com/hlamotte/strava-activity-recommender.git --branch gh-pages --single-branch gh-pages
+  #      cp -r docs/_build/html/* gh-pages/
+  #      cd gh-pages
+  #      touch .nojekyll
+  #      git config --local user.email "action@github.com"
+  #      git config --local user.name "GitHub Action"
+  #      git add .
+  #      git commit -m "Update documentation" -a || true
+  #      # The above command will fail if no changes were present, so we ignore
+  #      # that .
+  #  - name: Push changes
+  #    uses: ad-m/github-push-action@master
+  #    with:
+  #      branch: gh-pages
+  #      directory: gh-pages
+  #      github_token: ${{ secrets.GITHUB_TOKEN }}
+  sphinx-docs:
+    name: Check sphinx docs on Linux
+    runs-on: "ubuntu-latest"
+    defaults:
+      run:
+        shell: bash -l {0}
     steps:
-    - uses: actions/checkout@v1
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        docs-folder: "docs/"
-        build-command: "sphinx-build -E -b html -d _build/doctrees   . _build/html"
-    
-    - name: Commit documentation changes
+    - uses: actions/checkout@v2
+    - name: Install ctwrap
       run: |
-        git clone https://github.com/hlamotte/strava-activity-recommender.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that .
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-
+        pip install -e .
+    - name: Install Sphinx dependencies
+      run: |
+        cd docs
+        pip install -r requirements.txt
+        sphinx-build -b html . _build
